services:
  api:
    container_name: LibreChat
    build:
      context: .
      dockerfile: Dockerfile.multi
      target: api-build
      args:
        NODE_MAX_OLD_SPACE_SIZE: ${NODE_MAX_OLD_SPACE_SIZE:-6144}
    image: librechat-local-api
    ports:
      - "${PORT:-3080}:${PORT:-3080}"
    depends_on:
      - mongodb
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      NODE_ENV: production
      MONGO_URI: mongodb://mongodb:27017/LibreChat
      RAG_API_URL: ""
      MEILI_HOST: ""
    volumes:
      - type: bind
        source: ./librechat.yaml
        target: /app/librechat.yaml
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs

  mongodb:
    container_name: chat-mongodb
    image: mongo:8.0.20
    restart: unless-stopped
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth